# =============================================================================
# Local/Minikube Monitoring Resource Overrides
# =============================================================================
# Reduces memory requirements for local development on minikube.
# =============================================================================

# Prometheus local overrides
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: search
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
# Grafana local overrides
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: search
spec:
  template:
    spec:
      containers:
        - name: grafana
          # https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/#minimum-hardware-requirements
          # Minimum hardware requirements for Grafana:
          # Disk space: 1 GB
          # Memory: 750 MiB (approx 750 MB)
          # CPU: 250m (approx 0.25 cores)
          resources:
            requests:
              memory: "750Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "800m"
---
# OpenSearch Exporter local overrides
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-exporter
  namespace: search
spec:
  template:
    spec:
      containers:
        - name: exporter
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"

